name: Test
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Run unit tests
        run: |
          yarn
          yarn test
      - name: Post coverage report
        uses: romeovs/lcov-reporter-action@v0.2.16
        if: ${{ github.event_name == 'pull_request' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}